
version: "3.8"

services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      ./Flight_system/.env

    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000